In [21]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import svm
from sklearn.model_selection import GridSearchCV

In [22]:
#La fuente de datos proporcionada es https://archive.ics.uci.edu/ml/machine-learning-databases/voting-records/
#Utilizamos los datos del fichero .data, y asignamos los nombres de las columnas descritos en .names
data = pd.read_csv("auto-mpg.data",delim_whitespace=True,names=['mpg',
'cylinders',
'displacement',
'horsepower',
'weight',
'acceleration',
'model year',
'origin',
'car name'])

data.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino

In [23]:
#Definimos qué valores del dataset son las características y cuál el objetivo
caracteristica = ["cylinders",
"displacement",
"horsepower",
"weight",
"acceleration",
"model year",
"origin",
"car name"]
objetivo = "mpg"

In [24]:
from sklearn.preprocessing import LabelEncoder
data['car name'] = LabelEncoder().fit_transform(data['car name'])
data=data.replace('?', np.nan).ffill()

car_train, car_test, tar_train, tar_test = train_test_split(data[caracteristica],
data[objetivo],test_size = 0.25,random_state=2) 

car_train.head()

,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
275,6,163.0,125.0,3140.0,13.6,78,2,298
332,4,89.0,62.00,1845.0,15.3,80,2,281
29,4,97.0,88.00,2130.0,14.5,71,3,95
109,4,140.0,72.00,2401.0,19.5,73,1,63
243,3,80.0,110.0,2720.0,13.5,77,3,181

In [25]:
#Para buscar la configuración más óptima, 
#Definimos dos posibles tipos de kernel. Un kernel radial y otro lineal
kernels=['rbf','linear']
#Definimos varios valores de C, que determinan el tamaño del softmargin, para probar cuál de ellos es más óptimo
cs=[0.001, 0.10, 0.1, 1, 10]
#Definimos varios valores de gamma, que determinan el radio de influencia de cada punto
gammas=[0.001, 0.01, 0.1, 1]

#Inicializamos las variables que guardarán los mejores valores encontrados
maxscore=-100
maxkernel=''
maxcs=0
maxgamma=0
for i in kernels:
    for j in cs:
        for k in gammas:

            model=svm.SVR(kernel=i,C=j, gamma=k)
            model.fit(car_train, tar_train) 

            pred = model.predict(car_test)
            scor=model.score(car_test, tar_test)
            if(scor>maxscore):
                maxscore=scor
                maxkernel=i
                maxcs=j
                maxgamma=k
                
print("Se ha conseguido un score de "+
      str(maxscore)+" utilizando los parámetros: C: "+str(maxcs)+", Kernel: "+maxkernel+", Gamma: "+str(maxgamma))

Se ha conseguido un score de 0.8561186597597743 utilizando los parámetros: C: 1, Kernel: linear, Gamma: 0.001